C;cover size:124; local alignment length=124 (original info = e4pofA2	110	9.27	2.1	3)
>P1;e4pofA2
structureX:e4pofA2: 5: : 110: : : : : 
PETLMVKDIGAEHINKLIQVEGIVTRVGEIK-------P--------NFQSFRIQDRPETLKGGEMPRFIDGILLDDIVDVALPGDRVIVTGILRVVLEKRE---KTPIFRKILEVNHIE-----------------PVSK*

C;query_length:124 num_of_temps:1 cover_ratio:1 cover:124 not_cover:0
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHK-WVIQEEIKDA--G--------------DKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
