C;cover size:149; local alignment length=149 (original info = 3D4RA	153	251	1e-67	0)
>P1;3D4RA
structureN:3D4RA: 8: : 153: : : :6.0: 
GKIPKIYVEGELNDGDRVAIEKDGNAIIFLEKDEEYSGNGKLLYQVIYDDLAKY-SLDTLKKDVLIQYPDKHTLTYLKAGTKLISVPAEGYKVYPI-DFGFRVLKGYRLATLESKKGDLRYVNSPVSGTVIF-NEIPSERANYVFYLEE-*

C;cover size:149; local alignment length=149 (original info = 3D4RB	152	250	2e-67	1)
>P1;3D4RB
structureN:3D4RB: 7: : 152: : : :6.0: 
GKIPKIYVEGELNDGDRVAIEKDGNAIIFLEKDEEYSGNGKLLYQVIYDDLAKY-SLDTLKKDVLIQYPDKHTLTYLKAGTKLISVPAEGYKVYPI-DFGFRVLKGYRLATLESKKGDLRYVNSPVSGTVIF-NEIPSERANYVFYLEE-*

C;cover size:149; local alignment length=149 (original info = 3D4RE	146	243	3e-65	2)
>P1;3D4RE
structureN:3D4RE: 3: : 146: : : :6.0: 
GKIPKIYVEGELNDGDRVAIEKDGNAIIFLEK--EYSGNGKLLYQVIYDDLAKY-SLDTLKKDVLIQYPDKHTLTYLKAGTKLISVPAEGYKVYPI-DFGFRVLKGYRLATLESKKGDLRYVNSPVSGTVIF-NEIPSERANYVFYLEE-*

C;query_length:150 num_of_temps:1 cover_ratio:0.99 cover:149 not_cover:1
>P1;T0397
 : : : : : : : : : 
MKIPKIYVEGELNDGDRVAIEKDGNAIIFLEKDEEYSGNGKLLYQVIYDDLAKYMSLDTLKKDVLIQYPDKHTLTYLKAGTKLISVPAEGYKVYPIMDFGFRVLKGYRLATLESKKGDLRYVNSPVSGTVIFMNEIPSERANYVFYMLEE*
