C;template; converted from global alignment
>P1;d2fath2
structureX:d2fath2: 1: : 95: : : : : 
AKTTPPSVYPLAPGNSMVTL------------GCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQ-------------SDLYTLSS---------SVTVPSSTWPSETVTCN-VAHPASSTKVDKKIAAA-------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-----------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAE--KTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
