C;template; converted from global alignment
>P1;e1ep3B1
structureX:e1ep3B1: 1: : 101: : : : : 
-------------------------SQLQEMMTVVSQREVAYN----IFEMVLKGTLV---DEMDLPGQFLHLAVPNGAMLLRRPISISSWDKRAKTCTILYRIGDETTGTYKLSKLESGAKVDVMGPLGNGF*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK--TTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-------*
