C;template; converted from global alignment
>P1;e2k5vA1
structureX:e2k5vA1: 1: : 98: : : : : 
--------MNYKISELMPNLSGTINAEVVAAYPKKEFSRKDGTK-----GQLKSLFLKDD-------TGSIRGTLWNELADFEVKKGDIAEVSGYVKQGYSGLEISVDNIGIIEKS------LE----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEA----SHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
