C;template; converted from global alignment
>P1;d1bfoa2
structureX:d1bfoa2: 1: : 107: : : : : 
RANAAPTVSIFPPSTEQLATGGASVV------CLMNKFYPRD-----ISVKWKIDGTERNGVLNSVTDQDSADSTYSMSSTLSLTKA-------------DYQSHNLYTCQVVHKTSSSPVV-AKNFNRNEC---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKD----------AGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
