C;template; converted from global alignment
>P1;d2co7b2
structureX:d2co7b2: 1: : 80: : : : : 
KGTPEDVAGNLRWVET---------GNKLKVENPTPFYMNLASVTVGGKPITGLEYV-------------PPFADKTLNHGD-------------------IEWRVITDFGGESHPFHYVL--------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
----MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPT-NGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
