C;template; converted from global alignment
>P1;d2j43a1
structureX:d2j43a1: 1: : 104: : : : : 
-------------------ASH----------HLRHFKTLPAGESLGSLGLWVWGDVDQPSKD-WPNGAITTKAKKD----DYGYYLDVPLAAKHRQQVSYLINNKAGENLSKDQHISLLTPKNEVWIDENYHAHAYR*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQ-VILEASHMKGMKGATAEIDS---AEKTTVYMVDYTSTTS---GEKVK-----NHKWVTEDELSAK--*
