C;template; converted from global alignment
>P1;e3pieD4
structureX:e3pieD4: 1: : 117: : : : : 
LPINKEFPKGSKVVFLGDYAYG---GEATVDGYNSETRLKLTVKKGSLRAEPNIGKVRAKLDSQALRFYPVVSLESDSLTKASMAAVESEIIKYVSLPDSSEQKKLAKVPREAILNAESS----------------------------------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDK------------------------------------TLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
