C;template; converted from global alignment
>P1;d2ep6a1
structureX:d2ep6a1: 1: : 126: : : : : 
DVKDVGILQVKVLKAADLLAADFSGKSDPFCLLELGNDRLQTHTVYKNLNP----------EWNKVFTFPIKD-----IHDVLEVTVFDEDGDKPPDFLGKVAIPLLSIRDGQPNCYVLKNKDLEQAFKGVIYLEMDLIYN------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MK-VGS---QVIINTS----HMKGMKGAEATVT---GAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMK------GATAEIDSAEKTTVYMVDYTSTTS-----GEKVKNHKWVTEDELSAK*
