C;template; converted from global alignment
>P1;e3u28C1
structureX:e3u28C1: 1: : 92: : : : : 
--PPDTVLE---------------MGAF---LHPC------------EGDIVCRSINTKIPY----FNAPIYLENK------TQVGKVDEILGPLNEVFFTIKCGDGVQATSFKEGDKFYIAADKLLPIERFLP*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAE---KTTVYMVDYTSTTS--GEKVKNHKWVTEDELSAK-----*
