C;template; converted from global alignment
>P1;e2dyiA1
structureX:e2dyiA1: 1: : 85: : : : : 
MR---LVEI------------GRFGAPYALKGGLRFRGEP---VVLHLERVYVEGH---------------------------GWRAIEDLYRVGEELVVHLAGVTDRTLAEALVGLRVYAEVADLPPLE*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAE-KTTVYMVDYTSTTS---GEKVKNHKWVTEDELSAK--*
