C;template; converted from global alignment
>P1;d2nn6g1
structureX:d2nn6g1: 1: : 88: : : : : 
RYVPVKGDHVI-------------GIVTAKSG-DIFKVDVGGS----------------------------EPASLSYLSFEGATKRNRPNVQVGDLIYGQFVVANKD-----MEPEMVCIDSCGRANGMGVIGQ*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGA-TAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-------*
