C;template; converted from global alignment
>P1;e3it9A1
structureX:e3it9A1: 1: : 94: : : : : 
---FETVTPIKP------DATFVTQRVWFGDKSEVNL--------------GAGEA------------GSVTIPRGQL---KNLKASYTLTEPQLTAPLKKGQVVGTIDFQL--NGKSIEQRPLIVMENVEEGG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKT---------TVYMVDYTSTTSGEKVKNHKWVTEDELSAK-*
