C;template; converted from global alignment
>P1;e3j7aF1
structureX:e3j7aF1: 1: : 83: : : : : 
-QVGSLVMVTAGHSVGR-------------VGVISSIDKNMGTY------------------------DIIHVKD--------SRNKVFATRLSNVFVIGDN---------TKPYISLPREKGIKLDIIEERRNRLKA-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDE---------------LSAK*
