C;template; converted from global alignment
>P1;e3j21B2
structureX:e3j21B2: 1: : 92: : : : : 
MGKSLIQQRRGKGSPTFKSPSHRFRGAVKYIPLNYTQEKTLRGVVE--------EIMHDPGRTA----------------------------------------PVARVKFENGIEKLIIAPEGLLVGQEIYIGP---DAPIA--*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---------MKVGSQVIINTSHMKGM------------KGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
