C;template; converted from global alignment
>P1;e3eyfA1
structureX:e3eyfA1: 1: : 109: : : : : 
----MEIVLTQSP--------ATLSLSPGER---ATLSCRASQSVGGYLTWYQHKPGQAPRLLIFDASIRATGIPARFSGSGSGTDFTLTITRLEPED-----------FAVYYCQQRSMWPPVTFGQGTKLEIK-----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDA-------------GDKTL---QPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
