C;template; converted from global alignment
>P1;e2yt6A1
structureX:e2yt6A1: 1: : 84: : : : : 
---------------GV----TIFVALY-------DYEARTTE------------------DLSFKKGERFQIINNTEGD--WWEARSIATGKSGYIPSNYVVPAD--SIQAEEWYFGKMGRKDAESGPSSG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--------*
