C;template; converted from global alignment
>P1;e4ba6A1
structureX:e4ba6A1: 1: : 127: : : : : 
GADSG-EIILFSGSNHADFKAWGGDDWP---------SAFEISPKYEPKLD----LNKNFEIKVDYNGA--------DIVLIFARWDK---DIW-----AQISPYYVVDGTAVFTKEQIAKAYGSDDFSGLDYIAVKPLPSEEGVTVTKVSGIYTNG----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MKVGSQVIINTS--HMK----GMKGAEATVTGAYDTTAYVVS--YTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVD-----------------------YT-----STTSGEKVKNHKWVTEDELSAK*
