C;template; converted from global alignment
>P1;e2chhA1
structureX:e2chhA1: 1: : 113: : : : : 
-AQQGVFTLPAN-------------TSFGVTAFA-----------NAANTQTIQVLVDNVVKATFTGSGTSDKLLGSQVLNSGSGAIKIQVSVN---GKPSDLVSNQTILANKLNFAMVGSEDGTDNDYNDGIAVLNWPLG------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQ----------------PGD--QVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTS-----GEKVKNHKWVTEDELSAK*
