C;template; converted from global alignment
>P1;e4cknB2
structureX:e4cknB2: 1: : 115: : : : : 
---EPQTLLETTVMVSTKMPPHE-PQVRPLGVYVRTGRGGPNGVTRVVLVRLTDPTDPF----FLFELELLEDDGASAY-----------------ELSFVLNSSNRGTLRVLETTDEKTVEHISLVLLRQGDAGLKRYL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINT-----SHMKGMKGAEATVTGAYDTT--------AYVVSYTPTNGGQRVDHHKWVIQEEIK-DAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--*
