C;template; converted from global alignment
>P1;e4yngB2
structureX:e4yngB2: 1: : 99: : : : : 
PEIRTMKLEGGNDVSLKAGQ------------------TFTFTTDKSV--IGNSEMVAVTYEGFTT----DLSVGNTVLVDDGLI------GMEVTAIEGNKVICKVLNNG----DLGENKGVNLPGVSIALP*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--*
