C;template; converted from global alignment
>P1;e2y3vB2
structureX:e2y3vB2: 1: : 124: : : : : 
---------------GPHMTE-----LLFNKRLQVLVKSKDTDERRSV--IRVSIELQLPSSPVHRKDLVVRLTDD----------------TDLYFLYNLIISEEDNPRFLLQLSSSSSAFDHSPSNLNIVETNAFKHLTHLSLKLLPGSDTDIKKYLASC*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSG-----------------------------EKVKNHKWVTEDELSA---K------*
