C;template; converted from global alignment
>P1;e2oyzA1
structureX:e2oyzA1: 1: : 91: : : : : 
--------------------SIKENSYFAGGVKSLGFNQHGQDVSVGVLPGEYTFGTQAPERTVVKGALVVKRVGEADWTTYSSGESFDVEGN-------SSFEL-QVKDATAYLCEYL----------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRV------------DHHKWVIQE----EIKDA-GDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
