C;template; converted from global alignment
>P1;e4pofA2
structureX:e4pofA2: 1: : 110: : : : : 
FYNLPETLMVK-------DIGAEHINKLIQVEGIV----TRVGEIKPNFQSFRIQDRPETLKGGEMPRFIDGILLDDIVDVALPGDRVIVTG--------------------ILRVVLEKREKTPIFRKILEVNHIEPVSK*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDK-----------------TLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
