C;template; converted from global alignment
>P1;d1l4ia2
structureX:d1l4ia2: 1: : 77: : : : : 
VIPPEQAPGKLEFT------------RELTLFNPTPYYLTVTDLKAGNK----------SLE---NTMVPPQ---------------GKVTVNIGGDITYKTI---NDYGALTEQVRGVV--------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
----MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
