C;template; converted from global alignment
>P1;e5t89X3
structureX:e5t89X3: 1: : 106: : : : : 
----NTIIDVQISTPRP----------VKLLRGHTLVLNCTATTPLNTRVQMTWSYPDE-------KNKRASVRRRIDQSHANIFYSVLTIDKMQNKDKGLYTCRVRSGPSFKSVNTSVHIYDKAFI--*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGS---QVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK--TTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
