C;template; converted from global alignment
>P1;e3dm3A1
structureX:e3dm3A1: 1: : 98: : : : : 
---------DTYNIGELSPGMTATFEGEVISALPIKEFKRADGSI-----GKLKSFIVRDE-------TGSIRVTL------WDNLTDIDVGRGDYVRVRGYIREGYYGGLECTANYVEILKKGE----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGM-KGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKV----KNHKWVTEDELSAK*
