C;template; converted from global alignment
>P1;e3csbA1
structureX:e3csbA1: 1: : 89: : : : : 
----TNLEVVAATPT-----SLLISWDAYSSSYYVYYYRITYGETGGNSPV----------------------QEFTVPGS------KSTATISGLKPGVDYTITVYAGHYLYGLLSSPISINYR--T-------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVT-----GAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGE------KVKNHKWVTEDELSAK*
