C;template; converted from global alignment
>P1;e3luuA1
structureX:e3luuA1: 1: : 87: : : : : 
----------SDPR------TQPLEIRPLISRVEVDWA----------------------------DGHTSRLTFEHLRVECPC--AQIVTGKEHVSVVEVVPV--GHYAVQLHFSDGHNTGIFTWEYLRRLDAE*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTED-----------ELSAK*
