C;template; converted from global alignment
>P1;d2cp3a1
structureX:d2cp3a1: 1: : 71: : : : : 
LRLGDRVLVGGTKT-------GVV-------RYVGETDFAK-------GEWCGVELDEPLGKNDGAVAGTRYFQCPPKFGL--------FAPIHKVIRIG------------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
