C;template; converted from global alignment
>P1;e5ftcA2
structureX:e5ftcA2: 1: : 108: : : : : 
LGEQEIRNYDIVIKDKFPESSIPCDLHLKLRVGARVMSLVNDSLKGYYNGMLGIVTALEDNVITVRMDNGRT--IKFERYTWSNTQYTLK-------------------------DNEIVKEEIGSCTQFPLTLA--------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-----------------------------MKVGSQVIINTSHMKG--MKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
