C;template; converted from global alignment
>P1;e4gz9A4
structureX:e4gz9A4: 1: : 117: : : : : 
DKCGGTIKIEN-------------PGYLTSPGYPHSYHPS------EKCEWLIQAPEPYQRIMINFNPHFDLEDRDCKYDYVEVIDGENE-----GGRLWGKFCGKIAPSPVVSSGPF---LFIKFVSDYETHGAGFSIRYEIF*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQE-----------EIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---------*
