C;template; converted from global alignment
>P1;e3dmkC19
structureX:e3dmkC19: 1: : 84: : : : : 
---PLSAKIDPPTQTVDFGRPAVFTC-------QYTGNP------IKTVSWMKDGKAIGHS------ESVLRIESV-------------KKEDKGMYQCFVRNDRESAEASAELKLGGR-----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
