C;template; converted from global alignment
>P1;e2yujA1
structureX:e2yujA1: 1: : 113: : : : : 
---------------GSSGSSGIPRVFQNRFSTQY--RCFSVSMLAGP------------------NDRSDVEKGGKIIMPPSALDQLSRLNITY--PMLFKLTNKNSDRMTHCGVLEFVADEG--ICYLPHWMMQNLLLEEGGLVQVESVN*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGA-------EATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASH--------MKGMKGATAEIDS---AEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK----------*
