C;template; converted from global alignment
>P1;e2mwcA1
structureX:e2mwcA1: 1: : 102: : : : : 
---TAKNTVVRG-------LENVEALEGGE----ALFECQLSQPEVAAHTWLLDDEP-------VRTSENAEVVFFENGLRHLLLLKNLRPQDSCRVTFLAGDMVTSAFLTVRGGLE--HHHHHH----------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEAS-----H------MKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
