C;template; converted from global alignment
>P1;e2derA3
structureX:e2derA3: 1: : 86: : : : : 
M--SVGLIAQQLHWVDREPFTGTMRCTVKTRYRQTDIPCTVKALDDD-----RIEVIFDE----PVAAVTPGQSAVFYNGEVCLG----GGIIEQRLPLPV----------------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHM----KGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHM-KGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
