C;template; converted from global alignment
>P1;d1u5ka1
structureX:d1u5ka1: 1: : 78: : : : : 
-----------------------RSRTANRSGIVIRRRVTPAGDII-----VTL--LTPQ-------G-KLKAIA---RGGVKGPLSSSLNLFHHVGVQVYQGPHDLASVKQ------AVLEGAL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-*
