C;template; converted from global alignment
>P1;e1wooA1
structureX:e1wooA1: 1: : 83: : : : : 
-------------------------------RKLVALELSGKRI-ARKGYEVLKNGER-----------VGEITSGNFSPTLGKSIALALVSKSVKIGDQLGVVFPGGK-----LVEALVVKKPFYRGSVR*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKG---ATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKW-VTEDELSAK---*
