C;template; converted from global alignment
>P1;e1pmiA3
structureX:e1pmiA3: 1: : 107: : : : : 
LQEFPRSKGDAVKSVLYDPPIAEF---SVLQTIFDKSKGGKQVIEGLNGPS-----IVIATN-------------GKGTIQITGDD-----STKQKIDTGYVFFVAPGSSIELTADSANQDQDFTTYRAFVEA-----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYM-----VDYTST--TSGEKVKNHKWVTEDELSAK*
