C;template; converted from global alignment
>P1;e5vebY1
structureX:e5vebY1: 1: : 107: : : : : 
----YETFVCEKAKAD-------------QLIQTLHAVDKDD--PYSGHQFSFSLAPEA------ASGSNFTIQDNK----DNTAGILTRKNGYNRHEMSTYLLPVVISDNDYPVQSSTGTVTVRVCACPLEVLFQ*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSA-----EKTTVYMVDYTSTTSGE-----KVKNHKWVTEDELSAK--*
