C;template; converted from global alignment
>P1;d1kula_
structureX:d1kula_: 1: : 108: : : : : 
CTTPTAVAVTF---------DLTATTTYGENIYLVGSISQLGDWETSDGIALSADKYTSSDPLWYVTVTLPAG--------ESFEYK-------------------------FIRIESDDSVEWESDPNREYTVPQACGTSTATVTDTWR*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGG-------------QRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGE----KVKNHKWVTEDELSAK---------*
