C;template; converted from global alignment
>P1;d1oo2a_
structureX:d1oo2a_: 1: : 116: : : : : 
-RCPLMVKILDAV--KGTPAGSVALKVSQKTADGGWTQIATGVTDATGEIHNLITEQQFPAGVYRVEFDTKAYWTNQGSTPFH--EVAEVV-----------FDAHPEGHGH-YTLALLLSPFS--YTTTAVVSS------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVG-SQVIINTSHMKGMKGAEATVT--GAYDTTAYVV---SYTPTNG-------GQRVDHHKWVIQEEIKDA----GDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
