C;template; converted from global alignment
>P1;d1h6ta1
structureX:d1h6ta1: 1: : 81: : : : : 
----------------------------ECLNKPINHQSN----------LVVPNTVKNTDGSLVTPEIISDDGDYEK------PNVKWHLPEFTNEVSFIFYQPVTIGKAKARFHGRVTQPLKE--*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQP---GDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
