C;template; converted from global alignment
>P1;d1cvra1
structureX:d1cvra1: 1: : 82: : : : : 
---PTEMQVTA---------PANISASAQTFEVACDYNGAIATLSDDGDMVG--TAIVK-------------DGKAIIKLNE---------SIADETNLTLTVVGYNKV----TVIKDVKVE-------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSY-----TPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
