C;template; converted from global alignment
>P1;e3qtgA3
structureX:e3qtgA3: 1: : 94: : : : : 
PSIRVGSTSPINVQEGE------------------VVKFKLSDKSDGT----YIPVPNKAFFS----AVEQNDVILMLDGRL------RLKVTNTGSDWIEAVAESSG----VITGGKAIVVEGKDYDIS*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--MKVG--SQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--*
