C;template; converted from global alignment
>P1;e2f1lA1
structureX:e2f1lA1: 1: : 89: : : : : 
----DLVVI------------GKIVSVYGIRGEVKVYSFTDPLDNLLDYRRWTLRR----------DGEI-------------RQAELVRGRLHGKVLAAKLKGLDDREEARTFTGYEICIPRSELPS-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK-TTVYMVDYTSTTSG---EKVKNHKWVTE-DELSAK*
