C;template; converted from global alignment
>P1;e2wzpR1
structureX:e2wzpR1: 1: : 110: : : : : 
MLEANVYDNFNP-NYYNISDFSMPNGKKEKRGLPIPKARCQVIN---YELWETGYLYTS------SATLTVSVEV----------GDIVQILFPEVVPIEEALGKKKKLNLDMVYLVTDVDESNKATLKN------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---------MKVGSQVIINTSHMKGM---------KGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
