C;template; converted from global alignment
>P1;e2w9xB4
structureX:e2w9xB4: 1: : 108: : : : : 
KPLPLHIGGRVLVESPA-----NQPVSYTYSWPAVYFETAFKGQS-----------LTLKFDDD-QNIF----RLIVDD-----KAPVVINKPGKVDYPVHRVRLEKLTETQSTSGRFLGFYTDPSAKPLALPK*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
----MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSG--EKVKNHKWVTEDELSAK----*
