C;template; converted from global alignment
>P1;d1mfbl2
structureX:d1mfbl2: 1: : 101: : : : : 
PKSSPSVTLFPPSSEELETNKATLV------CTITDFYPGV-----VTVDWKVDGTPVTQG-------METTQPSKQ-----------SNNKYMASSYLTLTARAWERHSSYSCQVTHEGHTVEKSLSRA*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTS--GEKVKNHKWVTEDE----LSAK*
