C;template; converted from global alignment
>P1;e2fqpA1
structureX:e2fqpA1: 1: : 92: : : : : 
-----------------KRPGAIPTVQIDNERVKVTEWRFPPGGETGWHRHSDYVVVPTTGPLLLETPEGSVTSQLTRGVSYTRPE-------GVEHNVINPSDTEFVFVEIEIKA-------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHK---WVIQE-----EIKDAGDK---TLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
