C;template; converted from global alignment
>P1;e2vpvA1
structureX:e2vpvA1: 1: : 94: : : : : 
ENFALEIMFDKHKEYFASGILKLPAISGQKKLSNSFRTYITFHVIQGIVEVT-------VCKNKFLSV------------KGSTFQIPA-------FNEYAIANRGNDEAKMFFVQVTVS------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--MKV------------GSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
