C;template; converted from global alignment
>P1;d1wfma_
structureX:d1wfma_: 1: : 138: : : : : 
GSSGSSGSWNQAPKLHYCLDYDCQKAELFVTRLEAVTSNHDGGCDCYVQGSVANRT------GSVEAQTALKKRQLHTTWEEGLVLPLAEEELPTATLTLTLRTCDR-----------FSRHSVAGELRLGLDGTSVPLGAAQWG---ELKTSGPSSG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--------MKVGSQVIINTSHMKGMKGAEATVTGAYD------TTAYVVSYTPTNGGQRVDHHKWVIQEEIK-DAGDKTLQPG--------------DQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-----*
