C;template; converted from global alignment
>P1;e4ca9A1
structureX:e4ca9A1: 1: : 98: : : : : 
FQGAMAMFWGLNMKPERKYSQTIIKSFHISGVALDK-------GQEAKLYLAAEKQEYIVATVTK--------AIPQVALDLN------FSKGDRIMF---------------YTAGDASVSLLGYLHDIDSGS---------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
------------MKVG-------------SQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
