C;template; converted from global alignment
>P1;e4afdA1
structureX:e4afdA1: 1: : 127: : : : : 
---GADIVLFSGS-------------------KHVEFTDWGGTD------WPSAYELQPPYQTMPFDLNKNFEIKVDYSGADIVLIFARWEH---GSKPQIW--AQSPYYVVDGTAVFTKEQIAKAYGSDDFSDLDYIGVKPLPSADGMTVTKIVASYTS-----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDK---TLQPG----------DQVILEASHMKGMKGATAEIDSAEKTTVYMVDYT----------------------------STTSGEKVKNHKWVTEDELSAK*
