C;template; converted from global alignment
>P1;e2x10A7
structureX:e2x10A7: 1: : 95: : : : : 
NQTE----------------PPKVRLEGRSTTSLSVSWSIPPPQQSRVWKYEVTYRKKGD--------SNSYNVRRTE------GFSVTLDDLAPDTTYLVQVQALTQEGQGAGSKVHEFQT---LSP-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTN-GGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTS---GEKVKNHKWVTEDELSAK*
