C;template; converted from global alignment
>P1;d2cp0a1
structureX:d2cp0a1: 1: : 83: : : : : 
GGNLMLSALGLRLGDRVLLDGQ-----------KTG---TLRFCGTTEFAS-------GQWVGVELDEPEGKNDGSVGGVRYFICPPKQG---------------LFA------------SVSKISKAVDA---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
----------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
