C;template; converted from global alignment
>P1;d2c35b1
structureX:d2c35b1: 1: : 94: : : : : 
-RPFKGEVVD-----------AVVTQVNKVGL-----FTEIGPMS----CFISRHSIPSE--MEFDPNSNPPCYKT-------MDEDIVIQQDDEIRLKIVGTRVDKNDIFAI--GSLMDDYLGLV*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPG--DQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
