C;template; converted from global alignment
>P1;e4zkdA1
structureX:e4zkdA1: 1: : 107: : : : : 
SRKTNTLKLLALRLIKLSIQTHALSDPVDLGSELLLYHNLTH----NAVKLVKILGTNDISI----------NPNQSLIVEVEIIEPDFALNVIDSKYITNN-----------IVLTSIDHKVIAVGRIACQ-------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---------------------------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
