C;template; converted from global alignment
>P1;e3hqxA1
structureX:e3hqxA1: 1: : 104: : : : : 
SAQF---DHVTVIK-----------KSNVYFGGLCISHTVQFEDGTKKTLGVILPTEQPLTFETHVPEREIISGECRVKIADSTESELFRAGQSFYVPGN-------SLFKI-ETDEVLDYVCHLE----------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRV----------------DHHKWVIQEEIK----D-AGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
