C;template; converted from global alignment
>P1;e4jmqA3
structureX:e4jmqA3: 1: : 103: : : : : 
MRLPDP--YTNPEYPGLG---------FESVNLV-------DNDPISAQYWGINISYPELFPDEYAFLDSDLFITTT------GSEKPVFNG---ILFRTKLMNGDSFGSTLNNNGTYSGISLSLRESLE*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQ-PGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTS-GEKVKNHKWVTEDELSAK----*
