C;template; converted from global alignment
>P1;e3mfdA3
structureX:e3mfdA3: 1: : 86: : : : : 
-HYQTYLIAKKGDIPKLKGT------FYESKAFIKRDITYLLTEE--EKE--NVKINTTLLKPKKAWEKDASKIPDIVGH------EIFNDATIAKVPIYYEN------------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYV---VSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
