C;template; converted from global alignment
>P1;d1m9sa3
structureX:d1m9sa3: 1: : 86: : : : : 
--RYDKMEYDKGV-----TAYARVRNASGNSVWTKPYNTA---------------------------GAKHVNKLSVY---QGKNMRILREAKTPITTWYQFSIG----GKVI---GWVDTRALNTFYKQ*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAE---KTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---*
