C;template; converted from global alignment
>P1;e3khdA4
structureX:e3khdA4: 1: : 84: : : : : 
--------------------PEIRTGFLKLKLVTDYEFLGD-----ETCIACSYKKLPQS-----VKPNIILIADGSV------SCKVLETHEDHVITEVL-----NAVIGERKNMNLPNVKVDL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-*
