C;template; converted from global alignment
>P1;e3a3jA1
structureX:e3a3jA1: 1: : 92: : : : : 
---------------------------FETFKTLEA------------GKEISEQRVYYGDKNSVKLGAFMDHFITIPKGKQ---SEVKARYELADKNLQAPLAKGQVIGKVVYALD--GKDIASANLQVMNDVGE-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKT----LQPGDQVILEASHMKGMKGATAEIDSAEKT---------TVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
