C;template; converted from global alignment
>P1;e2xr4A1
structureX:e2xr4A1: 1: : 116: : : : : 
MERDGTFNLPPH-------------IKFGVTALTHA-----------ANDQTIDIYIDDDPKPAATFKGAGAQDQNLGTKVLDSGNGRVRVIVMANGRPSRLGSRQVDIFKKSYFGIIGSEDGADDDYNDGIVFLNWPLG------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQ-----------------PG---DQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTS--GEKVKNHKWVTEDELSAK*
