C;template; converted from global alignment
>P1;d3bwuc2
structureX:d3bwuc2: 1: : 84: : : : : 
LPPDQAAEKLRFRRS---------ANSLTLINPTPYYLTVTELN----------AGTRVLE---NALVPPMGESTVKLPS-------------DAGSNITYR--TINDYGALTPKMTGVME------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
