C;template; converted from global alignment
>P1;e2yrpA1
structureX:e2yrpA1: 1: : 114: : : : : 
GSSGSSGLPQVEAYSPSACSVRGGEELVLTGSN--------------FLPDSKVVFIERGPD----GKLQWEEEATVNR----LQSNEVTLTLTVPEYS-----NKRVSRPVQVYFYVSNGRRKRSPTQSFRFLPVICKEE---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--------------------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
