C;template; converted from global alignment
>P1;e3h9nA1
structureX:e3h9nA1: 1: : 89: : : : : 
----HIEVV------------GKLGSTYGIRGW-LRIYSSTEQAESIFDYQPWFLKIKG------------------------EWQSIELENWRYHNHEIIVKLKGVDDREAAQILANVEIGVDLSVFPE*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGG-QRV-DHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKT-TVYMVDYTSTTS---GEKVKNHKWVTEDELSAK*
