C;template; converted from global alignment
>P1;d2j73a1
structureX:d2j73a1: 1: : 102: : : : : 
----------------------------TETTIVVHYHRYDGKYDGWNLWIWPVEPVSQEGKAYQFTGED-----------DFGKVAVVKLPMDLTKVGIIVRLNEWQAKDVAKDRFIEIKDGKAEVWILQGVEEIFYEKP*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVD-HHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK-TTVYMVDYTSTTSGE-----------KVKNHKWVTEDELSAK----*
