C;template; converted from global alignment
>P1;d2j44a2
structureX:d2j44a2: 1: : 103: : : : : 
-----------------------------DNYFRIHVKKLPEENKDAQGLWTW-DDVEKP-SENWPNGALSFKDAKKDD--YGYYLDVKLKGEQAKKISFLINNTAGKNLTGDKSVEKLVPKMNEAWLDQDYKVFS*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAE---KTTVYMVDYTSTT---SGEKVK------NHKWVTEDELSAK*
