C;template; converted from global alignment
>P1;e1ddgA3
structureX:e1ddgA3: 1: : 119: : : : : 
----------------IHTSPYSKDAPLVASLSVNQKITGRNSEK---DVRHIEIDLGDS-GLRYQPGDALGVWYQTPRLYSIASSQAEVENEVHVTVGVVRYDVEGR-----ARAGGASSFLADRVEEEGEVRVFIEHNDNFR*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGM--KGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK------------------*
