C;template; converted from global alignment
>P1;e3w5mA5
structureX:e3w5mA5: 1: : 109: : : : : 
-----ALRVTSPSVEYVQRP-----LGLDAAHPRLSWPMASAAPGRRQSAY------------------QVRVASSAAGLSHPDVWDSGKVVSDDSVLVPYAGPPLKPRTRYFWSVRVWDADGGASEWSAPSWWETG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTT--SGEKVKNHKWVTEDELSAK-----------*
