C;template; converted from global alignment
>P1;e5iazA1
structureX:e5iazA1: 1: : 118: : : : : 
-RTVSGVCADVS----------------------------EYHPNIKNWQIESYGEPE-------FHTAKVHLKCAPGQ----TISAIKFASFGTPLGTCGTFQQGECHSINSNSVLERKCIGLERCVVAISPSNFGGDPCPEVMKRVAVEAVCSTAA----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAE---------------------------------KTTVYMVDYTSTTSG-----EKVKNHKWVTEDELSAK*
