C;template; converted from global alignment
>P1;e4kksA2
structureX:e4kksA2: 1: : 94: : : : : 
--LSDYLSL---------------NGDVDTTKQILTYVSE-------------------KYISNIKVGNDAIIEVGAYSNEK-FKAKVSEISPILDSKSRTIEVYLTPIGSNLDKLIIGMFSKIK-LITKRF---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK-----TTVYMVDYTSTTSGE------KVKNHKWVTEDELSAK*
