C;template; converted from global alignment
>P1;e1ctoA1
structureX:e1ctoA1: 1: : 109: : : : : 
GSSLEPPMLQALDIGPDVVSHQPGCLWLSWKP---------WKPSEYMEQECELRYQPQLK-----GANWTLVFHLPSS----------------------KDQFELCGLHQAPVYTLQMRCIRSSLPGFWSPWSPGLQLRPTMK*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-------------------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--*
