C;template; converted from global alignment
>P1;e1wxuA1
structureX:e1wxuA1: 1: : 93: : : : : 
---GSSGSSGTNWASGED-DHVVARAEY-------DFVAVSDE------------EI------SFRAGDMLNLALKEQQPKVRGWLLASLDGQTTGLIPANYVKILGKRRGRK---------TIESGPSSG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKG--ATAEIDSAEKTTV---YMVDYTSTTSGEKVKNHKWVTEDELSAK--*
