C;template; converted from global alignment
>P1;e4fqpA3
structureX:e4fqpA3: 1: : 92: : : : : 
--YPPEVSISGYD--------NNWYLGQNEATLTCD---ARSNPEPTGYNWSTTMGPLPP--FAVAQGAQLLIRPV-------------DKPINTTLICNVTNALGARQAELTVQVKEGP----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
