C;template; converted from global alignment
>P1;e1fx7A1
structureX:e1fx7A1: 1: : 86: : : : : 
---------------GADDA----------NLVRLT--ELPAGS---PVAVVVR-QLTEHVQGDIDLITRLKDAGVVPNARVTVETTPGGG---VTIVI--------------PGHENVTLPHEMAHAVKVEKV-----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDA-----------GDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSG----EKVKNHKWVTEDELSAK*
