C;template; converted from global alignment
>P1;e4jzoE3
structureX:e4jzoE3: 1: : 106: : : : : 
----SYVLTQPPSVSVSPGQTARITCSGDKLGDKYASWYQQKPGQSP----VLVIYQDNKR---------------------PSEIPARFSGSNSGNTATLTISGAQAMDEADYYCQAWDSNTGVFGTGTKLTVL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTT--AYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---------*
