C;template; converted from global alignment
>P1;e3eivB1
structureX:e3eivB1: 1: : 111: : : : : 
MAGETVITVVG-NLV--DDPELRFTPSGAAVAKFRVASTPRTDGESLFLTCSVWRQAAENVAESLQRGMRVIVQG-----------RLKQRSYEDREGVKRTVYELDVDEVGASLRSATAKVTKT-----------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK-----TTVYMVDYTSTTS-------GEKVKNHKWVTEDELSAK*
