C;template; converted from global alignment
>P1;d1nkga1
structureX:d1nkga1: 1: : 87: : : : : 
YVAASGRGKVA-----------GTASGADSSMDWVVHWYNDA------AQYWTYTSSSGSFTSPAMKPGTYTMVYYQGEY-------AVATSSVTVS---------AGSTTTKNISGSVK------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGD-QVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
