C;template; converted from global alignment
>P1;e3a21A7
structureX:e3a21A7: 1: : 93: : : : : 
-AGGAYAATSTGRYT------GVTAASTGLNVVDVAYTNNTSSART----ATLQ-----------VNGQTATTVSFPPTGASAGTVSVEVSLSKGSANTLALSGGPATEGITVRP------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKT---TVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
