C;template; converted from global alignment
>P1;e2mw1A1
structureX:e2mw1A1: 1: : 96: : : : : 
LKNG-ELKVEAE---G--G--SSLFACKNYKSFWISSVKEEGKFKENTSYKEFDGGWYLVK-IEDN-------ELKVIINRNET----------NASRSFTVCV------EAGNAFDEFKFVQDAAKQ--*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQR-VDHHK-----WVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
