C;template; converted from global alignment
>P1;e1cwvA4
structureX:e1cwvA4: 1: : 91: : : : : 
---PTLTGILVNGQNFATDKGFP---KTIFKNATFQLQMDNDVANN--TQYEWSSS------------FTPNVSVNDQ-------GQVTITYQTYSEV-AVTAKSKKFPSYSVSYRFYP-------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTS--HMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
