C;template; converted from global alignment
>P1;e3mzeA1
structureX:e3mzeA1: 1: : 100: : : : : 
-----------------------LTWGFRFFETVNPLKVG---------KEFASEPVWFGDSDRASLGVDKDVYLTIPRGRM---KDLKASYVLNSSELHAPLQKNQVVGTINFQLD--GKTIEQRPLVVLQEIPEG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTL----QPGDQVILEASHMKGMKGATAEIDSAEK---------TTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
