C;template; converted from global alignment
>P1;d1tdqa3
structureX:d1tdqa3: 1: : 86: : : : : 
----------------LDSPRDLMVTASSETSISLIWTKASGP----IDHYRITFTPSSGI------SSEVTVPRD------RTSYTLTDLEPGAEYIISITAERGRQQSLE---STVDAF---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
