C;template; converted from global alignment
>P1;e5chxA2
structureX:e5chxA2: 1: : 106: : : : : 
--SGERI----------------------SRIHLVSEP---------SITHFLQVSWET-----LESGFVITLTDGHSAWTGTVSESEISQEADDMAMEGYVGELRALLSGAGDVYTFNFSESCYFFFENLDV---------SFRLGSFNLEV---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMK--------------------------------GMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
