C;template; converted from global alignment
>P1;e2dduA1
structureX:e2dduA1: 1: : 112: : : : : 
LTLKPGYVLQFKL--------NIGCTSQFSSTAPVLLQYSHDAGM------SWFLVKEGCFPASAGKGCEGNSRELSEPTVYYTGDFEEWTRITIAIPRS--LASSKTRFRWIQEVPPFGLD------------GVYISE------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGD--------------------KTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
