#!/usr/bin/perl -w
##################################################################
#Remove uncessary gaps at the ends of both query and template
#in the alignments generated by clustalw.
#input: clustalw alignment file
#output: the input file will be overwritten if there is a problem
#Author: Jianlin Cheng
#Date: 10/05/2005.
##################################################################
if (@ARGV != 1)
{
	die "need one parameter: input clustal alignment file.\n";
}
$clustal = shift @ARGV;
open(CLU, $clustal) || die "can't read input clustal file.\n";
@align = <CLU>;
close CLU;

if (@align != 6)
{
	die "format error in clustal alignment: should have six lines.\n";
}
$line1 = shift @align;
$line2 = shift @align;
$line3 = shift @align;
$line4 = shift @align; #seq1
$line5 = shift @align; 
$line6 = shift @align; #seq2;

$rep4 = "";
$rep6 = "";
$len = length($line4);
$len == length($line6) || die "alignment length doesn't match.\n";
for ($i = 0; $i < $len; $i++)
{
	if (substr($line4, $i, 1) ne "-" || substr($line6, $i, 1) ne "-")
	{
		$rep4 .= substr($line4, $i, 1);
		$rep6 .= substr($line6, $i, 1);
	}
}

open(CLU, ">$clustal") || die "can't read input clustal file.\n";
print CLU "$line1$line2$line3$rep4$line5$rep6";
close CLU;


