#!/usr/bin/perl
###############################################################################
#Replace the chian id (position 22) of single-chain models generated by trRosetta with a space character
###############################################################################
if (@ARGV != 1)
{
	die "need one parameters: pdb file\n";
}
$pdb_file = shift @ARGV;
open(PDB, $pdb_file) || die "can't read pdb file.\n";
@atoms = <PDB>;
close PDB;
open(PDB, ">$pdb_file") || die "can't overwrite pdb file.\n";
foreach $atom (@atoms)
{
	$len1 =  length ($atom);
	if ($atom =~ /^ATOM\s+/)
	{
		$new_atom = substr($atom, 0, 21) . " " . substr($atom, 22);
		$len2 = length($new_atom);
		$len1 == $len2 || die "the length of atom lines does not match.\n";
		print PDB $new_atom;
	}
}
print PDB "END\n";
close PDB;

