C;cover size:98; local alignment length=98 (original info = 1AUZA	116	0	2.0e-07	0)
>P1;1AUZA
structureN:1AUZA: 1: : 102: : : :6.0: 
-----------SLGIDMNVKESVLCIRLTGELDHHTAETLKQKVTQSLEKDDIRHIVLNLEDLSFMDSSGLGVILGRYKQIKQIGGEMVVCAISPAVKRLFDMSGLFKIIRFE*

C;query_length:109 num_of_temps:1 cover_ratio:0.9 cover:98 not_cover:11
>P1;T0993s2
 : : : : : : : : : 
MHHHHHHENLYFQSESLSWMQTGDTLALSGELDQDVLLPLWEMREEAVK----GITCIDLSRVSRVDTGGLALLLHLIDLAKKQGNNVTLQGVNDKVYTLAKLYNLPADVLPR*
