C;cover size:326; local alignment length=326 (original info = 3EPKA	402	457	e-129	342	0.32	0.51	0.06)
>P1;3EPKA
structureX:3EPKA: 2: : 337: : : : : 
------KKVIVIAGTTGVGKSQLSIQLAQKFNGEVINSDSMQVYKDIPIITNKHPLQEREGIPHHVMNHVDWSEEYYSHRFETECMNAIEDIHRRGKIPIVVGGTHYYLQTLFNK----RVDTKSSERKLTRKQLDILESTDPDVIYNTLVKCDPDIATKYHPNDYRRVQRMLEIYYKTGKKPSETFNEQKITLKFDTLFLWLYSKPEPLFQRLDDRVDDMLERGALQEIKQLYEYYSQNKFTPEQCENGVWQVIGFKEFLPWLT--VKLEDCIERMKTRTRQYAKRQVKWIKKMLIPDIKGDIYLLDATDLSQWDTNASQRAIAISNDFISNRPIKQERAPKALEEL*

C;query_length:332 num_of_temps:1 cover_ratio:0.98 cover:326 not_cover:6
>P1;T0416
 : : : : : : : : : 
MTEMTKPFLIVIVGPTASGKTELSIEVAKKFNGEIISGDSMQVYQGMDIGTAKVTTEEMEGIPHYMIDILPPDASFSAYEFKKRAEKYIKDITRRGKVPIIAGGTGLYIQSLLYNYAFEDESISEDKMKQVKLKLKELEHLNNNKLHEYLASFDKESAKDIHPNNRKRVLRAIEYYLKTKKLLSSRKKVQQFTENYDTLLIGIEMSRETLYLRINKRVDIMLGHGLFNEVQHLVEQGFEA--------SQSMQAIGYKELVPVIKGNISMENAVEKLKQHSRQYAKRQLTWFKNKM------NVHWLNKERMS--LQMMLDEITTQINKRSSNHDCKRKHPRPSTREL*
