C;template; converted from global alignment
>P1;3IUGA
structureX:3IUGA: 1: : 184: : : : : 
-------------------GERVFGCDLGEHLLNSGFEVPQVLQSCTAFIERYGIVDGIY---RLSGVASNIQRLRHEFDSEHVPDLTKEPYVQDIHSVGSLCKLYFRELPNP-----LLTYQLYEKFSDAVSAATDEER--------LIKIHDVIQQLP-------------------PPHYRTLEFLMRHLSLLADYCSITNMHAKNLAIVWAPNLLRSQSVVVEFILNHVDVLFS--------------------------*

C;query; converted from global alignment
>P1;T0443
 : : : : : : : : : 
MQPETSAQYQHRFSQAIRGGEAADGLPQDRLNVYIR----LIRNNIHSFIDRC------YTETRQYFDSKEWSRLKEGFVRDARA---QTPYFQE---IPGEFLQYCQSPPLSDGILALMDFEYTQLLAEVAQIPDIPDIHYSNDSKYTPSPAAFIRQYRYDVTHDLQEAETALLIWRNAEDDVMYQTLDGFDMMLLEIMGSSALSFDTLAQTLVEFMPKADNWKNILLGKWSGWIEQRIIIPSLSAISENMEGNSPSQNHLSA*
