C;cover size:519; local alignment length=519 (original info = 2NUBA	690	577	e-165	586	0.2	0.35	0.19)
>P1;2NUBA
structureX:2NUBA: 147: : 682: : : :3.20: 
-------------------------------------------------------------------------------------------------------------------------------------------------------------SEEGYFLLHLDLKFRIQPFETLQTLLER--FNPKRIRVKPIGIDFVGRVQDVFKAKEKGEEFFRLCMERSTHKSSKKA-----WEELLKNRELREKAFLVVL---YTYP------ATILKPVLTY----------VADIVRMEPGKRLNLIR-YILRRY----VKALRDYGWYISPEEERAKGKLNFKDTVLD---AKGKNTKVI-------TNLRKFLELC--RPFVKKDVLSVEIISVSVYKKLEWRKEEFLKELINFLKNKGIKLKIKGKSLILAQTREEAKEKLIPVINKIKDVDLVIVFLEEYPKVDPYKSFLLYDFVKRELLKKMIPSQVILNRTLKNENLKFVLLNVAEQVLAKTGNIPYKLKEIEGKVDAFVGIDISRITRDGKTVNAVAFTKIFNSKGELVRYYLTSYPAFGEKLTEKAIGDVF-SLLEKLGFKKG---SKIVVHRDGRLYRDEVAAFKKYGELYGYSLELLEIIKRNNPRFF-SNEKFIKGYFYKLSEDSVILATYNQVYEGTHQPIKVRKVYGELPVEVLCSQILSLT-LMNYSSFQPIKLPATVHYSDKITKLMLR-GIEPIKK---------*

C;query_length:685 num_of_temps:1 cover_ratio:0.76 cover:519 not_cover:166
>P1;T0487
 : : : : : : : : : 
MNHLGKTEVFLNRFALRPLNPEELRPWRLEVVLDPPPGREEVYPLLAQVARRAGGVTVRMGDGLASWSPPEVLVLEGTLARMGQTYAYRLYPKGRRPLDPKDPGERSVLSALARRLLQERLRRLEGVWVEGLAVYRREHARGPGWRVLGGAVLDLWVSDSGAFLLEVDPAYRILCEMSLEAWLAQGHPLPKRVR---------------NAYDRRTWELLRLGEEDPKELPLPGGLSLLDYHASKGRLQGREGGRVAWVADPKDPRKPIPHLTGLLVPVLTLEDLHEEEGSLALSLPWEERRRRTREIASWIGRRLGLGTPEAVRAQAYRLSIPKLMGRRAVSKPADALRVGFYRAQETALALLRLDGAQGWPEFLRRALLRAFGASGA-SLRLHTLHAHPSQGLAFREALRK---------------------------AKEE---------GVQAVLVLTPPMAWEDRNR-------LKALLLREGLPSQ-ILNVPLREEE-RHRWENALLGLLAKAGLQVVALSGAY-PAELAVGFDAG--GRESFRFGGAAC--AVGGDGGHLLWTLPEAQA-GERIPQEVVWDLLEETLWAFRRKAGRLPSRVLLLRDGRVPQDEFALALEALAREGIAYDLVSVRKSGGGRVYPVQGRLADGLYVPLEDKTFLLLTVHRDFRGTPRPLKLVHEAGDTPLEALAHQIFHLTRLYPASGFAFPRLPAPLHLADRLVKEVGRLGIRHLKEVDREKLFFV*
