C;cover size:128; local alignment length=128 (original info = 1VL7A	135	224.50	3.9e-35	3)
>P1;1VL7A
structureX:1VL7A: 3: : 134: : : :1.50: 
--------------------------------GFIQEFQSAIISTISE-QGIPNGSYAPFVIDDAKNIYIYVSGLAVHTKNIEANPLVNVLFVDDEAKTNQIFARRRLSFDCTATLIERESQKWNQVVDQFQERFGQIIEVLRGLADFRIFQLTPKEGRFVIGFG-----------------------------------------------------------------------------------------------*

C;query_length:254 num_of_temps:1 cover_ratio:0.5 cover:128 not_cover:126
>P1;T0506
 : : : : : : : : : 
MLDVAPPVITPR-GTKIEPSAGAPFEAVRVARDVLHTSRTAALATLDPVSGYPYTTATNIGIEPDGTPFFFAAGLTLHARNMETDARISVTL--APFGKGDALTLPRLTLVGRADRIGPDEVP--LAIARYIARYPKA-KLYLSLPDTRLYRLRTEGVQINGGPARNASNITPADLRTDLSGAEELMAAAESEATRLNAIKGEASRLAVLAGAKTGRWKITSIDPDGIDLASASDLARLWFAERVETLKQFEKALAQLLK*
