C;cover size:301; local alignment length=301 (original info = 3D8BA	281	475	e-134	301	0.93	0.93	0.06)
>P1;3D8BA
structureX:3D8BA: 1: : 281: : : : : 
--------------------------------------------------------ERLKNLEPKMIELIMNEIMDHGPPVNWEDIAGVEFAKATIKEIVVWPMLRPDIFTGLRGPPKGILLFGPPGTGKTLIGKCIASQSGATFFSISASSLTSKWVGEGEKMVRALFAVARCQQPAVIFIDEIDSLLSQ------ESSRRIKTEFLVQLDG----SEDRILVVGATNRPQEIDEAARRRLVKRLYIPLPEASARKQIVINLMSKEQCCLSEEEIEQIVQQSDAFSGADMTQLCREASLGPIRSLQT----------VRPIAYIDFENAFRTVRPSVSPKDLELYENWNKTFGCGK*

C;query_length:357 num_of_temps:1 cover_ratio:0.84 cover:301 not_cover:56
>P1;T0422
 : : : : : : : : : 
MHHHHHHSSGVDLGTENLYFQSMVPPIPKQDGGEQNGGMQCKPYGAGPTEPAHPVDERLKNLEPKMIELIMNEIMDHGPPVNWEDIAGVEFAKATIKEIVVWPMLRPDIFTGLRGPPKGILLFGPPGTGKTLIGKCIASQSGATFFSISASSLTSKWVGEGEKMVRALFAVARCQQPAVIFIDEIDSLLSQRGDGEHESSRRIKTEFLVQLDGATTSSEDRILVVGATNRPQEIDEAARRRLVKRLYIPLPEASARKQIVINLMSKEQCCLSEEEIEQIVQQSDAFSGADMTQLCREASLGPIRSLQTADIATITPDQVRPIAYIDFENAFRTVRPSVSPKDLELYENWNKTFGCGK*
