C;cover size:80; local alignment length=80 (original info = 5HOKA	83	0	1.6e-11	0)
>P1;5HOKA
structureN:5HOKA: 4: : 83: : : :6.0: 
NDVLVDAYNIAKDSQHVHGVHYIRGRNVGEDVHLAINIYVDADLKVFESDLVADAIRRKIEAEVDHVRDVHVGVTPVRIA-*

C;query_length:81 num_of_temps:1 cover_ratio:0.99 cover:80 not_cover:1
>P1;T0967
 : : : : : : : : : 
EDYIEAIANVLEKTPSISDVKDIIARELGQVLEFEIDLYVPPDITVTTGERIKKEVNQIIKEIVDRKSTVKVRLFAAQEEL*
