C;template; converted from global alignment
>P1;3D8BA
structureX:3D8BA: 1: : 281: : : : : 
--------------------------------------------------------ERLKNLEPKMIELIMNEIMDHGPPVNWEDIAGVEFAKATIKEIVVWPMLRPDIFTGLRGPPKGILLFGPPGTGKTLIGKCIASQSGATFFSISASSLTSKWVGEGEKMVRALFAVARCQQPAVIFIDEIDSLLSQE------SSRRIKTEFLVQLDGS----EDRILVVGATNRPQEIDEAARRRLVKRLYIPLPEASARKQIVINLMSKEQCCLSEEEIEQIVQQSDAFSGADMTQLCREASLGPIRSLQT----------VRPIAYIDFENAFRTVRPSVSPKDLELYENWNKTFGCGK*

C;query; converted from global alignment
>P1;T0422
 : : : : : : : : : 
MHHHHHHSSGVDLGTENLYFQSMVPPIPKQDGGEQNGGMQCKPYGAGPTEPAHPVDERLKNLEPKMIELIMNEIMDHGPPVNWEDIAGVEFAKATIKEIVVWPMLRPDIFTGLRGPPKGILLFGPPGTGKTLIGKCIASQSGATFFSISASSLTSKWVGEGEKMVRALFAVARCQQPAVIFIDEIDSLLSQRGDGEHESSRRIKTEFLVQLDGATTSSEDRILVVGATNRPQEIDEAARRRLVKRLYIPLPEASARKQIVINLMSKEQCCLSEEEIEQIVQQSDAFSGADMTQLCREASLGPIRSLQTADIATITPDQVRPIAYIDFENAFRTVRPSVSPKDLELYENWNKTFGCGK*
