C;cover size:325; local alignment length=325 (original info = 3EPKA	402	763.96	0	319	35	100.00)
>P1;3EPKA
structureX:3EPKA: 1: : 335: : : : : 
-----SKKVIVIAGTTGVGKSQLSIQLAQKFNGEVINSDSMQVYKDIPIITNKHPLQEREGIPHHVMNHVDWSEEYYSHRFETECMNAIEDIHRRGKIPIVVGGTHYYLQTLFNKRVDTKSSERKLTRKQL----DILESTDPDVIYNTLVKCDPDIATKYHPNDYRRVQRMLEIYYKTGKKPSETFNEQKITLKFDTLFLWLYSKPEPLFQRLDDRVDDMLERGALQEIKQLYEYYSQNKFTPEQCENGVWQVIGFKEFLPWLTV--KLEDCIERMKTRTRQYAKRQVKWIKKMLIPDIKGDIYLLDATDLSQWDTNASQRAIAISNDFISNRPIKQERAPKALE--*

C;query_length:332 num_of_temps:1 cover_ratio:0.98 cover:325 not_cover:7
>P1;T0416
 : : : : : : : : : 
MTEMTKPFLIVIVGPTASGKTELSIEVAKKFNGEIISGDSMQVYQGMDIGTAKVTTEEMEGIPHYMIDILPPDASFSAYEFKKRAEKYIKDITRRGKVPIIAGGTGLYIQSLLYNYAFEDESISEDKMKQVKLKLKELEHLNNNKLHEYLASFDKESAKDIHPNNRKRVLRAIEYYLKTKKLLSSRKKVQQFTENYDTLLIGIEMSRETLYLRINKRVDIMLGHGLFNEVQHLVEQGFE--------ASQSMQAIGYKELVPVIKGNISMENAVEKLKQHSRQYAKRQLTWFKNK------MNVHWLNKERMSL--QMMLDEITTQINKRSSNHDCKRKHPRPSTREL*
