C;cover size:73; local alignment length=73 (original info = 3IUGA	184	31.1	0.74	78	0.32	0.44	0.08)
>P1;3IUGA
structureX:3IUGA: 54: : 129: : : : : 
-----------------------------------------------------RHEFDSEHVPDLTKEPYVQDIHSVGSLCKLYFRELPNPLLTYQLYEKFSDAVSAATDEERLIKIHDVIQ--QLPPPHY--------------------------------------------------------------------------------------------------------------------------*

C;query_length:248 num_of_temps:1 cover_ratio:0.29 cover:73 not_cover:175
>P1;T0443
 : : : : : : : : : 
MQPETSAQYQHRFSQAIRGGEAADGLPQDRLNVYIRLIRNNIHSFIDRCYTETRQYFDSKEWSRL-KEGFVRDARAQTP----YFQEIPGEFLQYCQSPPLSDGILALMDFEYTQLLAEVAQIPDIPDIHYSNDSKYTPSPAAFIRQYRYDVTHDLQEAETALLIWRNAEDDVMYQTLDGFDMMLLEIMGSSALSFDTLAQTLVEFMPKADNWKNILLGKWSGWIEQRIIIPSLSAISENMEGNSPSQNHLSA*
