C;template; converted from global alignment
>P1;1VL7A
structureX:1VL7A: 1: : 135: : : : : 
-----------------------------YAGFIQEFQSAIISTISE-QGIPNGSYAPFVIDDAKNIYIYVSGLAVHTKNIEANPLVNVLFVDDEAKTNQIFARRRLSFDCTATLIERESQKWNQVVDQFQERFGQIIEVLRGLADFRIFQLTPKEGRFVIGFGA----------------------------------------------------------------------------------------------*

C;query; converted from global alignment
>P1;T0506
 : : : : : : : : : 
MLDVAPPVITPRGTKIEPSAGAPFEAVRVARDVLHTSRTAALATLDPVSGYPYTTATNIGIEPDGTPFFFAAGLTLHARNMETDARISVTLAPFGKGD--ALTLPRLTLVGRADRIGPD--EVPLAIARYIARYPKAKLYL-SLPDTRLYRLRTEGVQINGGPARNASNITPADLRTDLSGAEELMAAAESEATRLNAIKGEASRLAVLAGAKTGRWKITSIDPDGIDLASASDLARLWFAERVETLKQFEKALAQLLK*
