C;template; converted from global alignment
>P1;d1uwya1
structureX:d1uwya1: 1: : 97: : : : : 
---GVKGQVFDQNGNPLPNVIVEVQDRKHICPYRTN---KYG-------EYYLLL-----------LPGSYIINVTV-PGHDPHITKV---------IIPEKSQNFSALKKDILLPFQGPSCPMIPLYRNL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-------*
