C;template; converted from global alignment
>P1;d1phta_
structureX:d1phta_: 1: : 83: : : : : 
-------------------------AEGYQYRALYDYKKEREE------------DI------DLHLGDILTVNKGSLVALGFSDGQEARPEEIGWLNGYNETT-GERGDFPGTYVEYIGRKKISPP*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKV---KNHKWVTEDELSAK*
