C;template; converted from global alignment
>P1;e4hjjL3
structureX:e4hjjL3: 1: : 113: : : : : 
TVAAPEIVMTQSP--------ATLSV---SPGERATLSCRASESISSNLAWYQQKP----GQ-----APRLFIYTASTRAT---DIPARFSGSGSGTEFTLTISSLQSEDFAVYYCQQYNNWPSITFGQGTRLEIK*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEAS--HMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTED----------ELSAK*
