C;template; converted from global alignment
>P1;e4hh8A2
structureX:e4hh8A2: 1: : 95: : : : : 
-----KVAALGSD--------PHISKVQESGEIQLECTSVGW-YPEPQVQWQTHRGEEFPSS------ESRNPD---EEGLFTVRASVIIRDSSKNVSCAIRNLLLGQEKEVEVSIPA------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
