C;template; converted from global alignment
>P1;d2nq3a1
structureX:d2nq3a1: 1: : 131: : : : : 
SLTMKSQLQITVISAKLKENKWFGPSPYVEVTVDGQSKKTEKCNNTN-----SPKWKQPLTVI------VTPVSKLHFRVWSHQTLKSDVLLGTAALDIYETLKSNNMKLEEVVVTLQLGGDKEPTETIGDLSICLDGLQLE*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MKVG--SQVIINTSH--MKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEA--SHMKGMKG--ATAEID---------SAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
