C;template; converted from global alignment
>P1;e4be5A3
structureX:e4be5A3: 1: : 108: : : : : 
------PVIEANLSLNQNQLASNGGYISSQLGIRNESCETVKFK-----------YWL---SIKGPEGIYFPAKAVVGVDTAQM-------LNVTRGFWVPEYMADGKYTVSLQVVAENGKVFKANQEFVKGVDL---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSH------MKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVD--------YTSTTSGEKVKNHKWVTEDELSAK*
