C;template; converted from global alignment
>P1;e2wabA4
structureX:e2wabA4: 1: : 113: : : : : 
---NPGILYNGRFDFSDPNGPKCAWSGSNVELNFYGTEASVTIKSGGEN--------WFQAIVDGNPLPPFSVNATTSTVKLVSGLA-EGAHHLVLWKRTEASLGEVQFLGFDFGS-------------GKLLAAPKP*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTS------HMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQ--PGDQVILEASHMKGMKGATAEIDSAEK---TTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---*
