C;template; converted from global alignment
>P1;e4en8B2
structureX:e4en8B2: 1: : 120: : : : : 
-LADSTVNILDNLN--TSGTHYYTRQSPDVGNYISYQLTIPGDFNNIASSIFSFRTRN--NQGIGTLYRLTESINGYN----------LITINNYSDLLNNVEPI-SLLNGATYIFRVKVT----ELNNYNIIFDAYRNS-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATV-----TGAYDTTAYVV------------SYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
