C;template; converted from global alignment
>P1;e1wmdA1
structureX:e1wmdA1: 1: : 116: : : : : 
AYVNESSSLSTSQKATYSFTATAGKPLKISLVWSDAPASTTASVTLVNDLDLVITAPNGTQYVGNDFTSPYNDNWDGRNNVENVFINAPQS---------GTYTIEVQA-------YNVPVGPQTFSLAIVN------------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--------MKVGSQVIIN--------------TSHMKGMKGAEATVTGAYDTTAYV---VSYTPTNG-------GQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
