C;template; converted from global alignment
>P1;e2os7C3
structureX:e2os7C3: 1: : 114: : : : : 
----PDIKFAS--------KEYGVTIGESRIIY----PLDAAGVMVSVKNTQDYPVLIQSRIYDENKEKESEDPFVVTPPLFRLDAKQQNSLRIAQAGGVFPRDKESLKWLCVKGIPVGVFVQFA---INNCI---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRV-----DHHKWVIQEEIKDAGDKTLQPGDQVILEA-SHMKGMKGATAEIDSA------EKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
