C;template; converted from global alignment
>P1;d1n10a1
structureX:d1n10a1: 1: : 95: : : : : 
----TKVTFHVEKG-----------SNPNYLALLVKYVNGDGD--------VVAVDIKEKGKDKWIELKESWGAIWRIDTPDK--LTGPFTVRYTTEGGTKTEAEDVIPEG---------WKADTSYES-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQ-----PGDQVILEASHMKGMKG-ATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
