C;template; converted from global alignment
>P1;d1whoa_
structureX:d1whoa_: 1: : 94: : : : : 
---VPKVTF-------------TVEKGSNEKHLAVLVKYEGDT--------MAEVELREHGSDEWVA-------MTK---GEGGVWTFDSEEPLQGPFNFRFLTEKGMKNVFDDVVPEKYTIGATYAP-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVY-MVDYTSTTSGEKVKN----HKWVTEDELSAK*
