C;template; converted from global alignment
>P1;e4k91B1
structureX:e4k91B1: 1: : 93: : : : : 
---FESRNFYK------KGTELTKGLVWKGSEHEVKAGLAED--------------------------LTMTLPRGQM---QKLQASMVLEPQLMAPIQQGQVIGKVEVKLD--DKVIRSADLVALNAVEEGG*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSA--------EKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-*
