C;template; converted from global alignment
>P1;d1e8ya2
structureX:d1e8ya2: 1: : 135: : : : : 
CDRKF----RVKIRG--------IDIPVLPRNTDLTVFVEANIQHGQQVLCQRRTSPKPFTEEVLWNVWLEFS-IKIKDLPKGALLNLQI------------YCLLYYVNLLLIDHRFLLRRGEYVLHMWQISGFNADKLTSATNPDKENSMSISILLDN*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
----MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRV-----------DHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---------------------*
