C;template; converted from global alignment
>P1;e3d30A1
structureX:e3d30A1: 1: : 112: : : : : 
MAYDDLHEGYATYTGSGYSG----GAFLLDPIPSDMEITAINPADL---------------NYGGVKAALAGSYLEVEGPK--------------GKTTVYVTDLYPEGARGALDLSPNAFRKIGNMKDGKINIKWRVVKAPITG--*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGS----QVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTT-------------------SGEKVKNHKWVTEDELSAK*
