C;template; converted from global alignment
>P1;e2l3sA1
structureX:e2l3sA1: 1: : 93: : : : : 
--------------------VEYVRALF-------DFNGNDDEDL------------------PFKKGDILKIRDKPEEQWWNAEDMDGKRGMIPV-----PYVEKCRPSSASVSTLTGGNQDSSHPQPLGGPEPGPYAQPSI*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKG------MKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-------------*
