C;template; converted from global alignment
>P1;d1i1ca2
structureX:d1i1ca2: 1: : 102: : : : : 
TPRGPQVYTMAPPKEEMTQSQVSIT------CMVKGFYPPD-----IYTEWKMNGQPQEN----------YKNTPPTMDT-DGSYFLYSKLNVKKETWQQGNTFTCSVLHEGL-ENEHTEKSLSH------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEI-------DSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
