C;template; converted from global alignment
>P1;d2r83a1
structureX:d2r83a1: 1: : 123: : : : : 
-------------------------EKLGDICFSLRYVPTAG-------KLTVVILEAKNLKKMDVGGLSDPYVKIHLMQNGKRLKKKKTTIKKNTLNPYYNESFSFEVPFEQ-IQKVQVVVTVLDYDKIGKNDAIGKVFVGYNSTGAELRHWSDM*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVI-QEEIKDA--GDKTLQPGDQVILEASHM-KGMKGATAEIDSAEKTTVY----MVDYTSTTSGEKVKNHKWVTEDELSAK------------------------*
