C;template; converted from global alignment
>P1;e2kbnA1
structureX:e2kbnA1: 1: : 109: : : : : 
----------------MEPQLTKIVDIVENGQWANLKAKVIQLWENTHESISQVGLLGDETGIIKFTIWKNAELPLLEQGESYLLRS----------VVVGEYNDRFQVQVNKNSSIEKLSEPIEVGLEHHHHHH-------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTG------AYDTTAYVVSYTPTNGGQRVD------HHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVD------YTSTTSGEKVKNHKWVTEDELSAK*
