C;template; converted from global alignment
>P1;e3pyiA2
structureX:e3pyiA2: 1: : 109: : : : : 
---TSKIALFDQTLIASLLQPLSLNQPD-FKAYKTKVKLKISEQRNETSGEK----ELKFEISRSDDFEFLFSETLNNPTEINIIL--------------DAEKNFCSFELFSKTPISKGKIFSIKLHAVR------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINT-----SHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGD------KTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVY--MVDYTSTTSGEKVKNHKWVTEDELSAK*
