C;template; converted from global alignment
>P1;e3j39A6
structureX:e3j39A6: 1: : 96: : : : : 
MGRVIRAQRKGAGSVFKAHVKKRKGAAKLRSLDFAERSGYIRGVVKDIIHDPGRGAP-------LAV------------------VHFRDPYRY----------KIRKELFIAPEGMHTGQFVYCGRKA---TL---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
M---------KVGSQVIINTSHMKGMKG----AEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
