C;template; converted from global alignment
>P1;e5udb33
structureX:e5udb33: 1: : 112: : : : : 
-SFGAHALSPR-------TLTAQHLNKLVSVEGIVTKTSLV----RPDHQRITVQEMPEMSIDVILDDDLVDKTKPGDRVNVVGVFKSLGAGGMNQSNLIGFKTLILG------------NTVYPLHARSTGVAAR*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAG---------DKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---*
