C;template; converted from global alignment
>P1;d1d2oa2
structureX:d1d2oa2: 1: : 97: : : : : 
---GETSATVTKNWDDNNNQDGKRPTEIKVELYQDGKATGKTAILNESNN------W--THTWTGL--DEKAKGQQVKYTVEELTKVKGYTTHVDNNDMGNLITTNKYTP--------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGS-QVIIN-----TSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
