C;template; converted from global alignment
>P1;e1a3xA4
structureX:e1a3xA4: 1: : 102: : : : : 
PEIRTGTTTNDVDYPIPPNH------------------EMIFTTDDKYAKACDDKIMYVDYKNITK----VISAGRIIYVDDGVL------SFQVLEVVDDKTLKVKALNA---GKICSHKGVNLPGTDVDLP*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--*
