C;template; converted from global alignment
>P1;e4qxlA1
structureX:e4qxlA1: 1: : 115: : : : : 
AGEGAWQDSGMGVTLNYRGVSASSSPLS-ARQPVSGVMTLVA--WRYELNGPTPAG----------LRVRLCS---------QSRCVELDGQSGTTHGFAHVPA--VEPLRFVWEVPGGGRLIPALKVRSNQVIVNYRH---*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGS--------------QVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGE----KVKNHKWVTEDELSAK*
