C;template; converted from global alignment
>P1;e2eixB4
structureX:e2eixB4: 1: : 113: : : : : 
KREPALNPNEYKKFMLREKQIINHNTRLFRFNLHHPEDVVGLPIGQHMSVKATVDGKEIYRPYTPVSSDDEKGYFDLIIKVYEKGQMSQYIDHLNPGDFLQVRGPKG-------------------QFDYKP---------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-------MKVGSQVIINT------------------SHMKGMK-GAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGD---KTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
