C;template; converted from global alignment
>P1;d1a25a_
structureX:d1a25a_: 1: : 132: : : : : 
-ERRGRIYIQAHIDREV--LIVVVRDAKNLVPMDPNGLSDPYVKLKLIPDPKSESKQKTKTIKCSLNPEWNE------TFRFQLK--ESDKDRRLSVEIWDWDLTSRNDFMGSLSFGISELQKAGVDGWFKLLSQEEGEYFNV*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTA---------YVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEK------TTVYM--VDYTSTTSGEKVKNHKWVTEDELSAK--*
