C;template; converted from global alignment
>P1;e4e8dB5
structureX:e4e8dB5: 1: : 94: : : : : 
----------------TQGQPAFYAYDFTVEEPKDTYLDLSEF--GKGVAFVNGQNLGR----FWNVGPTLSLYIP---------HSYLKEGANRIIIFETEGQYKE-----EIHLTRKPTLKHIKGENL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTED----ELSAK--*
