C;template; converted from global alignment
>P1;e3n6wA2
structureX:e3n6wA2: 1: : 105: : : : : 
---------------SMACTIQKAE--ALDGAHLMQILWYDEEESLYPAVWLRDNCPC--SDCYLDSAKARKLLVEALD----VNIGI-KGLIFDRKKVYITWPDEHYSEFQADWLKKRCFSKQARAKL*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-----*
