C;template; converted from global alignment
>P1;e4fomA1
structureX:e4fomA1: 1: : 93: : : : : 
--YAPEVSVTGYDG--------NWFVGRKGVNLKCN---ADANPPPFKSVWSRLDGQWPDG---------LLASDN-------TLHFVHPLTFNYSGVYICKVTNSLGQRSDQKVIYISDPP----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSA--EKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
