C;template; converted from global alignment
>P1;e5nikD2
structureX:e5nikD2: 1: : 87: : : : : 
PVPTYQTLIV----------RPGDLQTDVKNVLTIPLSALGDPVGDNRYKVKLLR------------NGETR------------EREVTIGARNDTDVEIVKGLEAGDEV-----VIGEAKPGAAQ*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELS--AK*
