C;template; converted from global alignment
>P1;e1kzlA1
structureX:e1kzlA1: 1: : 92: : : : : 
----------------------MFTGLVEAIGVVKDVQGTIDN-------GFAMKIEAPQILDDCHTGDSIAVN--------GTCLTVT-DFDRYHFTVGIAPESLRLTNLGQCKAGDPVNLERAVLSST*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTT-----SGEKVKNHKWVTEDELSAK-*
