C;template; converted from global alignment
>P1;e2l6nA1
structureX:e2l6nA1: 1: : 132: : : : : 
---------------GMTPQSDTPKVTGLKLKRKSRQLEISFD----------------------------NGQQFTLSCELLRVYSPSAEVHGHGNPVLVTHKKNVNINAITPVGNYAVKLVFDDGHDTGLYSWKVLYDLASNQVDLWENYLARLRAAKASREPLIDMAVKYHT*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAE-----ATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHM----------------KGMKGATAEIDSAEKTTVYMVDYTSTTSGE-------------------------KVKNHKWVTEDELSAK-----*
