C;template; converted from global alignment
>P1;d1fnla1
structureX:d1fnla1: 1: : 84: : : : : 
EDLPKAVVFLEPQW---------YSVLEKDSVTLKCQGAYSP---EDNSTQWFHNESLISSQAS------SYFIDA-------------ATVNDSGEYRCQTNLSTLSDPVQLEV----------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
