C;template; converted from global alignment
>P1;d2j43a2
structureX:d2j43a2: 1: : 112: : : : : 
PLKEGYLRINYHNQSGHYDNLAVWTFKDVKTPTTDWPNGLDLSHKGHYGAYVDVPLKEGA---NEIGFLILDKSKTGDAIKVQPKDYLFKELDN---------------------------------HTQVFVKDTDPKVYNNPYYID*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKG-----------------AEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-------*
