C;template; converted from global alignment
>P1;e3h41A2
structureX:e3h41A2: 1: : 99: : : : : 
-----------------------SKAFIDVSAATLWTAPDSLRPIDVPSATNPVDLWKWTKSTL---DEKLWLTNANKLETQA-----LLGQEVTVVDKKGDWVKVLVHGQPTPRNEEGYPGWPEK-QLTY-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQR--------VDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
