C;template; converted from global alignment
>P1;e1pm4A1
structureX:e1pm4A1: 1: : 117: : : : : 
IPNIATYTGTIQGKGEVCIIGNKEGKTRG----------GELYAVLHSTNVNA----DMTLILLRNVGGNGWGEIKRNDIDKPLKYEDYYTSGLSWIWKIKN------------NSSETSNYSLDATVHDDKE---------DSDVLTKCPV*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
----------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAG---------------DKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK---*
