C;template; converted from global alignment
>P1;e3q0yC2
structureX:e3q0yC2: 1: : 112: : : : : 
QTGFDLSTATTLF-------------------WRPVPVHVKQQDREDVLEELTFRILTGVAKQNHNLRILRIHISSDSDLFFLHTLEVSEEDSPRF----QAVLTIRGGES---VFKIVEINDFKQLPHITLAFRPGN-------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
---MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKD----------------------------AGDKTLQPGDQVILEASHMKGMKGATAEIDSAE--KTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
