C;template; converted from global alignment
>P1;e3j7yD2
structureX:e3j7yD2: 1: : 118: : : : : 
ANFVSWKSRTKYTITPVKMRKSGGRDHTGRIRVHGIGGGHKQRYRMIDFLRFRPEET-------------------KSGPFEEKVIQVRYDPCRSADIALVAGGSRKRWIIATENMQAGDTILNSNHIGRMAVAARE*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-----MKVGSQVIINTSHM--KGMKGAEATVT-----GAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK-*
