C;template; converted from global alignment
>P1;e1ynxA1
structureX:e1ynxA1: 1: : 114: : : : : 
---TRPIFAIEQLSPYQN--VWTIKARVSYKGEIKTWHNQRGDGK------LFNVNFLDTSGE-----IRATAFNDFATKFNEILQEGKVYYVSKAKLQPAKPQFTNLTHPYELNLDRDT---VIEECFDESN------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGM-----KGATAEIDSAEKTTV----------YMVDYTSTTSGEKVKNHKWVTEDELSAK*
