C;template; converted from global alignment
>P1;e1ltlA1
structureX:e1ltlA1: 1: : 103: : : : : 
--ISN--------VIPLRELRSKFIGKFVAVDGIVRKTD----EIRPDTQTLKLQEPLENLSGGEQPRQITVVLEDDLVDTLTPGDIVRVTG---------TLRTVRDERTKRFKNFIY--------GNYTEFL-------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAG-----------------DKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
