C;template; converted from global alignment
>P1;e5al7A1
structureX:e5al7A1: 1: : 113: : : : : 
SYSAKMDYGKSVVNILPSV---------EMLVNFNGDMTRSSKRSCLLYAERVDFKELLQLRLTEKSDQRRMYITTVDLE----------LHLTTRDQNLSSGR----------EVHDYYLQFVEIRSDKNLVHLSLPCRSA----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-----MKVGS-QVIINTSHMKGMKGAEATVTGAYD------TTAYVVSYTPTNG----------GQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
