C;template; converted from global alignment
>P1;d2k5wa1
structureX:d2k5wa1: 1: : 108: : : : : 
ERASLNRIGKDVYYMQIKGE-------GTIEKVDGRNLRNYTLPAYDEDGV-----KKQITFRSTKKENDHKLNKYAFLRLYVDQDDNSK--------------------NEISSIEVKSYEEIQKADLPEKVKDKFTIK*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK--------*
