C;template; converted from global alignment
>P1;d1hxma2
structureX:d1hxma2: 1: : 86: : : : : 
SQPHTKPSVFVMKNG--------------TNVACLVKEFYPKD-----------IRINLVSSK-KITEFDPAIVISPSGK----YNAVKLGKYEDSNSVTCSVQHDN----KTVH--STDFE----*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
--MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
