C;template; converted from global alignment
>P1;d1q38a_
structureX:d1q38a_: 1: : 89: : : : : 
-------------MRGSNAPQP-----SHISKYILRWRPKNSVGRW----------------------KEATIPG-HL-----NSYTIKGLKPGVVYEGQLISIQQYGHQEVTRFDFTTTSTSTPGSRSHHHHHH*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTT--SGEKVKNHKWVTEDELSAK---------*
