C;template; converted from global alignment
>P1;e4k3uA2
structureX:e4k3uA2: 1: : 123: : : : : 
---GGIGWVYPANVKGQRMAAVRHNGNWQSLTSRNNTGDFPLGGILAH--TGSGGSMTLTASDGI----ASKQRVSLFAKPL-----LAEQTLTVNGNTVSANGGGWQVLDTGAALPLTIHTEMPWDIGFINIENPA-------------------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGA----------------------EATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKG----------ATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
