C;template; converted from global alignment
>P1;e2x8nA2
structureX:e2x8nA2: 1: : 87: : : : : 
-----------------------------STLRSVQYRSEEG--------VIVFI---------LANDRELKFRPDDLQATYGATPEQLREIEISPSGLGVYFETLEEDVSLIGLLEGRRGSAKWMAEHPLAS-*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATA--EIDSAEKTTVYMVDYTSTTSGEKV--------KNHKWVTEDELSAK*
