C;template; converted from global alignment
>P1;e5a2fA1
structureX:e5a2fA1: 1: : 103: : : : : 
WYTVNSAYGDTIIIPCRLDV------------PQNLMFGKWKYEKPDGSP---VFIAFRSSTKKSVQYDDVPEYKDRLNLSE-------NYTLSISNARISDEKRFVCMLVTEDNVFEAPTIVKV--------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-----MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPG--DQVILEASHMKGMKGATAEIDSAEK--TTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
