C;template; converted from global alignment
>P1;e2qm4A1
structureX:e2qm4A1: 1: : 81: : : : : 
EELEQGLLQPWAWLQLAE--------NSLLAKVFITKQGYALLVSDLQ---------QVWHEQVE------------ATFSCDCVA---------------DALILRVRSELSGLPFYWNFHCLA------*

C;query; converted from global alignment
>P1;T0579
 : : : : : : : : : 
-------MKVGSQVIINTSHMKGMKGAEATVTGAYDTTAYVVSYTPTNGGQRVDHHKWVIQEEIKDAGDKTLQPGDQVILEASHMKGMKGATAEIDSAEKTTVYMVDYTSTTSGEKVKNHKWVTEDELSAK*
